from pyformlang.cfg import CFG, Variable, Production, Epsilon


class CFGException(Exception):
    """
    Base exception for CFG utils
    """

    def __init__(self, msg):
        self.msg = msg


def read_cfg_from_file(filename: str, start_state: str):
    """
    Read and return a CFG from a file

    Parameters
    ----------
    filename: str
        Name of input file with CFG given in format:
        https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html#pyformlang.cfg.CFG.from_text
    start_state: str
        CFG start state

    Returns
    -------
    cfg: CFG
        CFG object read from file

    Raises
    ------
    CFGException
        If file with given filename is absent
    CFGException
        If CFG in file does not match required format
    """
    try:
        with open(filename, "r") as cfg_file:
            cfg_text = cfg_file.read()
            return CFG.from_text(cfg_text, Variable(start_state))

    except FileNotFoundError as exc:
        raise CFGException(f"Error: File '{filename}' not found") from exc

    except ValueError as exc:
        raise CFGException(
            f"Error: CFG form in '{filename}' might be corrupted, check the correctness of CFG"
        ) from exc


def add_missing_epsilon(initial_cfg: CFG, nf_cfg: CFG) -> CFG:
    """
    Complete normal form's production with EPS-productions from initial grammar

    Parameters
    ----------
    initial_cfg: CFG
        Initial CFG, before applying NCF algorithm
    nf_cfg: CFG
        CFG generated by pyformlang.cfg.CFG.to_normal_form() from initial_cfg

    Returns
    -------
    nf: CFG
        CFG supplemented with EPS-production (if necessary)
    """
    if initial_cfg.generate_epsilon():
        productions = set(nf_cfg.productions)
        productions.add(Production(nf_cfg.start_symbol, [Epsilon()]))
        nf_cfg = CFG(
            variables=nf_cfg.variables,
            terminals=nf_cfg.terminals,
            start_symbol=nf_cfg.start_symbol,
            productions=productions,
        )

    return nf_cfg


def transform_cfg_to_wcnf(cfg: CFG) -> CFG:
    """
    Transform given cfg into Weakened Normal Chomsky Form (WNCF)

    Parameters
    ----------
    cfg: CFG
       CFG object to transform to WNCF

    Returns
    -------
    wncf: CFG
        CFG in Weakened Normal Chomsky Form (WNCF)
    """
    return add_missing_epsilon(initial_cfg=cfg, nf_cfg=cfg.to_normal_form())
